"""
Google Calendar MCP Tools
These tools are exposed via MCP protocol and called by the LLM agent
when it needs to check availability or book appointments.

Tools:
- check_availability: checks free/busy slots for a given date
- book_appointment: creates a calendar event
"""

import os
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
from googleapiclient.discovery import build


def get_calendar_service():
    """
    Build and return an authenticated Google Calendar service.
    Uses token.json generated by setup_google_auth.py
    """
    if not os.path.exists('token.json'):
        raise FileNotFoundError(
            "token.json not found. Run setup_google_auth.py first."
        )

    creds = Credentials.from_authorized_user_file(
        'token.json',
        ['https://www.googleapis.com/auth/calendar']
    )

    # Auto-refresh token if expired
    if creds.expired and creds.refresh_token:
        creds.refresh(Request())
        with open('token.json', 'w') as f:
            f.write(creds.to_json())

    return build('calendar', 'v3', credentials=creds)


def check_availability(date: str) -> str:
    try:
        service = get_calendar_service()
        time_min = f"{date}T00:00:00+05:30"
        time_max = f"{date}T23:59:59+05:30"

        result = service.freebusy().query(body={
            "timeMin": time_min,
            "timeMax": time_max,
            "timeZone": "Asia/Kolkata",
            "items": [{"id": "primary"}]
        }).execute()

        busy_slots = result["calendars"]["primary"]["busy"]

        if not busy_slots:
            return "Available."

        busy_times = [f"{s['start'][11:16]}-{s['end'][11:16]}" for s in busy_slots]
        return f"Busy: {', '.join(busy_times)}. Other slots free."

    except Exception as e:
        return f"Error: {str(e)}"


def book_appointment(caller_name, service, start_time, end_time) -> str:
    try:
        calendar_service = get_calendar_service()

        event = {
            "summary":     f"{service} — {caller_name}",
            "description": f"Patient: {caller_name}\nService: {service}",
            "start": {"dateTime": start_time, "timeZone": "Asia/Kolkata"},
            "end":   {"dateTime": end_time,   "timeZone": "Asia/Kolkata"},
            "reminders": {"useDefault": True},
        }

        calendar_service.events().insert(
            calendarId='primary',
            body=event
        ).execute()

        date_str = start_time[5:10]
        time_str = start_time[11:16]
        return f"Confirmed. {caller_name}, {service}, {date_str} at {time_str}."

    except Exception as e:
        return f"Error: {str(e)}"